name: deploy frontend
#Deploy when push is made from frontend

on:
    push:
            branches: [ main ]
            paths: 
            - 'frontend/**'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Azure login
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Delete existing blobs in the storage account
    - name: Delete existing blobs
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name azureresumeflorian --auth-mode key -s '$web'
    
    # Setup Azure CLI
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
    # Upload to Blob Storage
        inlineScript: |
            az storage blob upload-batch --account-name azureresumeflorian --auth-mode key -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        # Purge CDN endpoint
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "CDNresume" --name "CDNendpointResume" --resource-group "ResumeChallenge"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()








