name: deploy_frontend
# Deploy when a push is made to frontend files in the main branch

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Azure login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Setup Azure CLI
      - name: Setup Azure CLI
        uses: azure/setup-azure-cli@v1

      # Upload to Blob Storage
      - name: Upload to Blob Storage
        run: |
          az storage blob upload-batch --account-name azureresumeflorian --auth-mode key -d '$web' -s frontend/
        
      # Purge CDN endpoint
      - name: Purge CDN endpoint
        run: |
          az cdn endpoint purge --content-paths "/*" --profile-name "CDNresume" --name "CDNendpointResume" --resource-group "ResumeChallenge"
        
      # Azure logout
      - name: Logout from Azure
        run: |
          az logout
        if: always()
